<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Memory Cards</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <script src="js/jquery-1.10.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/memoryGame.js"></script>
    <script src="js/autoPlay.js"></script>
</head>
<body>
<div class="container" style="padding: 0 160px;">
    <div class="row col-lg-12">
        <span style="font-size: 40px;">Memory Games</span>
        <button type="button" class="btn btn-danger col-md-offset-2 resetGame">Reset</button>
        <button type="button" class="btn btn-primary col-md-offset-1 autoPlay">Auto Play</button>
        <button type="button" class="btn btn-warning col-md-offset-1 timeSpent">00:00:00</button>
    </div> <!-- End Game control button -->
    <hr/>
    <div id="cardgrid" class="row"> <!-- div for ajax show cardgrid-->

    </div> <!-- End Cardgrid -->
</div> <!-- End Container -->

<!-- complete game dialog -->
<div class="modal fade" id="gameCompleted" tabindex="-1" role="dialog" aria-labelledby="gameCompletedLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="gameCompletedLabel">Congratulations!</h4>
            </div>
            <div class="modal-body">
                Congratulations, you have just completed the challenge.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
</body>
</html>
